* Intro
** Installing
   To install python to your computer you will need to install it at http://python.org/downloads/.
   When you get to the website, make sure you download version 3.5.1 and not version 2. After selecting version 3.5.1 you
   will go down til you see Files and will be asked the OS(Windows, Mac etc.) as well as the 32 or 64 bit version. If you are not
   sure what bit your computer is using then download 32 bit instead. If you are downloading for windows then make sure
   you click on executable installer. After downloading it make sure you click on the installer to install it on
   your computer and go through the steps. To make sure that you have python installed on your open of cmd(command prompt) and python.exe. If you
   get "Python 3.5.1" then python is properly installed onto your computer.
** IDE
   An integrated development environment(IDE) is a software application that is used by programmers
   to write and test code easily. The IDE we are using for python is PyCharm as it has a friendly
   interface and is easy to understand. You can install PyCharm at http://www.jetbrains.com/pycharm/
   and click on download. First select the OS(Windows, Mac, etc.) you are using and click on the
   download under community. After the installer is done, click on it and click next until you
   get to installation options. Click on .py and 32 or 64 bit depending on what your computer has.
   Make sure the folder is called JetBrain and click install.

* Programming
** TODO

* Robotics
** Setting up
    pip is a python package installer
    pulls packages from the web and sets them up on your system
*** PyFRC
    pyfrc is a python port of the Java API for FRC Robotics
    installing this package will install all necessary classes and functions for basic robot control, e.g. driving, using motors, firing pistons, etc.
    https://github.com/robotpy/pyfrc
    To install PyFRC open up command prompt (cmd). Next you type in "pip install pyfrc" if you are on windows
    or "pip3 install pyfrc" if you are on linux and press enter. Just wait for it to install and after it's done
    you close command prompt and you are good to go. (second picture is a placeholder due to pyfrc already
    installed on my computer so it shows that it's already installed on my computer.)
** Learning
    First few weeks learn python at codecademy https://www.codecademy.com/learn/python
    Here are the Units you should complete before working on robot code.
    -UNIT 1: PYTHON SYNTAX
    -UNIT 2: STRINGS AND CONSOLE OUTPUT
    -UNIT 3: CONDITIONALS AND CONTROL FLOW
    -UNIT 4: FUNCTIONS
    -UNIT 5: LISTS & DICTIONARIES
    -UNIT 7: LISTS AND FUNCTIONS
    -UNIT 8: LOOPS
    After getting a feel of python go to https://robotpy.readthedocs.org/en/latest/guide/index.html and read
*** Misc Info
    We currently use the IterativeRobot class for our robot, so learning and coding based off of those examples will be the most helpful
    We usually use Solenoids, Talons, and RobotDrive classes so looking into those classes would be the most helpful and productive.
    We have custom made classes for using Xbox controllers for our controllers, so learning how to use that would also be helpful: http://www.github.com/ROBOMonkeys/enums/
    
* Activities
** Ardublocks

* TODO 
    add info about git
    add documentation for XboxButtons/XboxAxis
    add pics(in progress)

    
