* Intro
** Installing
   To install python to your computer you will need to install it at http://python.org/downloads/.
   When you get to the website, make sure you download version 3.5.1 and not version 2. After selecting version 3.5.1 you
   will go down til you see Files and will ask be the OS(Windows, Mac etc.) as well as the 32 or 64 bit version. If you are not
   sure what bit your computer is using then download 32 bit instead. If you are downloading for windows then make sure
   you click on executable installer. After downloading it make sure you click on the installer to install it on
   your computer and go through the steps. To make sure that you have python installed on your open of cmd(command prompt) and python.exe. If you
   get "Python 3.5.1" then python is properly installed onto your computer.
** IDE
   Explain what an IDE is
   Install PyCharm community
   http://www.jetbrains.com/pycharm/

* Programming
** TODO

* Robotics
** Setting up
*** PIP
    pip is a python package installer
    pulls packages from the web and sets them up on your system
*** PyFRC
    pyfrc is a python port of the Java API for FRC Robotics
    installing this package will install all necessary classes and functions for basic robot control, e.g. driving, using motors, firing pistons, etc.
** Learning
   To start learning how to code for a basic robot go to  https://robotpy.readthedocs.org/en/latest/guide/index.html and read
*** Misc Info
    We currently use the IterativeRobot class for our robot, so learning and coding based off of those examples will be the most helpful
    We usually use Solenoids, Talons, and RobotDrive classes so looking into those classes would be the most helpful and productive.
    We have custom made classes for using Xbox controllers for our controllers, so learning how to use that would also be helpful: http://www.github.com/ROBOMonkeys/enums/
    

* TODO 
    add info about git
    add documentation for XboxButtons/XboxAxis
    add pics
    add activities and projects
    
